---

# install Mondoo Client
- include_tasks: pkg_debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: pkg_rhel.yml
  when: ansible_os_family == "RedHat"

- include_tasks: pkg_suse.yml
  when: ansible_os_family == "Suse"

- name: create mondoo config directory
  file:
    dest: /etc/opt/mondoo
    state: directory
  become: true
  when: not ansible_check_mode

- name: retrieves a new registration token
  command: mondoo client generate-token --expiresin 120
  connection: local
  register: retrievedRegistrationToken
  when: registration_token_retrieval == "cli"

- name: set registration token fact
  set_fact: registration_token={{ retrievedRegistrationToken.stdout }}
  when: registration_token_retrieval == "cli"

- name: log registration token
  ansible.builtin.debug:
    var: registration_token
    verbosity: 1

- name: unregister mondoo client
  # unregisters an existing Mondoo Client if it was registered
  command: mondoo unregister --force --config /etc/opt/mondoo/mondoo.yml
  args:
    # only run the command if no config file exists
    creates: /etc/opt/mondoo/mondoo.yml
  when: force_registration == true
  # if the credentials are already invalid, the command will throw an error
  ignore_errors: yes

- name: remove existing credentials
  # ensure no configuration file exists if force mode was activated
  file:
    state: absent
    path: /etc/opt/mondoo/mondoo.yml
  when: force_registration == true

- name: register Mondoo Client
  command: mondoo register --config /etc/opt/mondoo/mondoo.yml --token {{ registration_token }}
  args:
    # only run the command if no config file exists (was not deleted in non-force mode)
    creates: /etc/opt/mondoo/mondoo.yml
  become: true
  when: not ansible_check_mode
  notify: restart mondoo-service

- name: ensure mondoo service is running
  # ensures the systemd service is started and enabled
  ansible.builtin.systemd:
    name: mondoo.service
    state: started
    enabled: yes
  become: true
  when: not ansible_check_mode

- name: ensure Mondoo Client is managed
  command: mondoo register
  become: true
  when: ensure_managed_client == true and not ansible_check_mode