# download the latest json to fetch the latest released version

- name: determine latest released version
  ansible.windows.win_uri:
    url: "{{ latest_version_url }}"
    return_content: yes
  register: latest_jsondata
  when: pkg_version_url is undefined

- name: log latest version
  ansible.builtin.debug:
    var: latest_jsondata.json
  when: pkg_version_url is undefined

- name: determine latest pkg version
  set_fact:
    pkg_version_url: "{{ latest_jsondata.json | json_query(jmesquery) }}"
  vars:
    jmesquery: "files[*].filename | [?contains(@, 'msi')] | [0]"
  when: pkg_version_url is undefined

- name: log latest version
  ansible.builtin.debug:
    var: pkg_version_url

# download and install msi
# we do register as part of the msi workflow to support reregistration more easily
- name: install mondoo msi package
  win_package:
    path: "{{ pkg_version_url }}"
    state: present

- name: unregister Mondoo Client
  # unregisters an existing Mondoo Client if it was registered
  ansible.windows.win_command: mondoo.exe unregister --force --config C:\\ProgramData\\Mondoo\\mondoo.yml
  args:
    chdir: "C:\\Program Files\\Mondoo"
    # only run the command if no config file exists
    creates: C:\ProgramData\Mondoo\mondoo.yml
  when: force_registration == true
  # if the credentials are already invalid, the command will throw an error
  ignore_errors: yes

- name: remove existing credentials
  # ensure no configuration file exists if force mode was activated
  ansible.windows.win_file:
    state: absent
    path: C:\ProgramData\Mondoo\mondoo.yml
  when: force_registration == true

- name: register Mondoo Client
  ansible.windows.win_command: mondoo.exe register --config C:\\ProgramData\\Mondoo\\mondoo.yml --token {{ registration_token }}
  args:
    chdir: "C:\\Program Files\\Mondoo"
    # only run the command if no config file exists (was not deleted in non-force mode)
    creates: C:\ProgramData\Mondoo\mondoo.yml
  when: not ansible_check_mode

- name: ensure Mondoo Client is managed
  ansible.windows.win_command: mondoo.exe register
  args:
    chdir: "C:\\Program Files\\Mondoo"
  when: ensure_managed_client == true and not ansible_check_mode
