---
- name: Converge
  hosts: all
  roles:
    - role: ansible-mondoo
  vars:
    registration_token_retrieval: "manual"
    registration_token: "setregistrationtokenhere"

    # registration_token_retrieval: "cli"