---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  yamllint
  ansible-lint
  flake8
platforms:
  - name: ubuntu
    box: ubuntu/bionic64
  - name: centos
    box: centos/7
provisioner:
  name: ansible
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    # show which tests where executed in test output
    v: 1
