name: "Build Mondoo Package (Testing)"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version that should be released'
        required: true
        default: '1.2.3'

jobs:
  build-mondoo-payloads:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Create destination folder
        run: |
          cd  helper
          mkdir packages
          cp mondoo.sh  packages/
          cp mondoo.ps1 packages/

      - name: Install RPM tools
        run: |
          sudo apt update && sudo apt install -y rpm gpg

      - name: Authenticate with GCloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Setup GCloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Download Signing Keys
        env:
          KEY_PATH: ${{ runner.temp }}
        run: |
          gcloud --project=mondoo-base-infra secrets versions access latest --secret=gpg-package-signing-cert-public-2023 --out-file=${KEY_PATH}/public.gpg
          gpg --import ${KEY_PATH}/public.gpg
          gcloud --project=mondoo-base-infra secrets versions access latest --secret=gpg-package-signing-cert-private-2023 --out-file=${KEY_PATH}/private.gpg
          gpg --import --allow-secret-key-import ${KEY_PATH}/private.gpg

      - name: Check GPG Keys
        run: |
          gpg --list-keys
          gpg --list-secret-keys

      - name: Build Packages
        env: 
          VERSION: ${{ github.event.inputs.version }}
        run: |
          cd helper && make

      - name: Sign RPMs
        run: |
          cd helper/
          rpmsign --define='%_gpg_name Mondoo Inc' --addsign ./packages/*rpm

      - name: Generate Checksums
        run: |
          cd helper/packages
          sha256sum *linux* > checksums.linux.txt
          sha256sum *windows* > checksums.windows.txt
          sha256sum *darwin* > checksums.macos.txt

      - name: Upload files to releases.mondoo.com
        run: |
          gsutil cp -r helper/packages/* gs://releases-us.mondoo.io/mondoo/${VERSION}/



      - name: Upload files to Github Release Page
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: helper/packages/*

            
      - name: Create Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mondoo-${{ github.event.inputs.version }}
          path: helper/packages/
          retention-days: 7