name: Generate Mondoo releases

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version that should be released'
        required: true
        default: '1.2.3'

jobs:
  build-mondoo-payloads:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: make destination dir
        run: |
          mkdir dist
      - name: Tar up mondoo.sh
        run: |
          cp mondoo.sh mondoo
          tar czf dist/mondoo_${{ github.event.inputs.version }}_linux.tar.gz ./mondoo
          rm mondoo
      - name: zip up mondoo.ps1
        run: |
          zip dist/mondoo_${{ github.event.inputs.version }}_windows.zip mondoo.ps1
      - name: install RPM tools
        run: |
          apt install -y rpm
      - name: build RPM
        run: |
          ./build-rpms.sh ${{ github.event.inputs.version }} ./dist
      - name: build DEB
        run: |
          ./build-deb.sh ${{ github.event.inputs.version }} ./dist
      - name: save the files
        run: |
          echo "SAVE THE FILEs!!!"
