name: Update Docker Hub docs

on:
  push:
    branches:
    - master

jobs:
  dockerhub_docs:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    name: Update Docker Hub docs
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update mondoolabs/mondoo DockerHub docs
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: mondoolabs/mondoo
          readme-filepath: ./dockerhub/mondoolabs/mondoo.md

      - name: Update mondoo/client DockerHub docs
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: mondoo/client
          readme-filepath: ./dockerhub/mondoo/client.md
            

