name: Release Mondoo Edge Container Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Mondoo client version'     
        required: true

jobs:
  build_container:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Build Docker
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push root images (alpine)
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/386,linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          build-args: |
            BASEURL=https://releases.mondoo.com/edge/mondoo/${{ github.event.inputs.version }}
            VERSION=${{ github.event.inputs.version }}
          target: root
          tags: |
            mondoo/client:edge-${{ github.event.inputs.version }}
            mondoo/client:edge-latest

      - name: Build and push rootless images (alpine)
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/386,linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          build-args: |
            BASEURL=https://releases.mondoo.com/edge/mondoo/${{ github.event.inputs.version }}
            VERSION=${{ github.event.inputs.version }}
          target: rootless
          tags: |
            mondoo/client:edge-${{ github.event.inputs.version }}-rootless
            mondoo/client:edge-latest-rootless

      - name: Start mondoo-operator integration tests
        run: |
          curl -s \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.REPO_API_TOKEN }}" \
            https://api.github.com/repos/mondoohq/mondoo-operator/actions/workflows/31262606/dispatches \
            -d "{\"ref\":\"main\",\"inputs\":{\"mondooClientImageTag\":\"edge-${{ github.event.inputs.version }}-rootless\"}}"
