name: Mondoo Docker Latest

on:
  push:
    branches:
      - master

jobs:
  build_container:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    name: Build Docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mondoolabs/mondoo
          tags: latest