name: Release Powershell Module

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-2022
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Publish Powershell Module
        shell: powershell
        env:
          NUGETAPIKEY: ${{ secrets.NUGETAPIKEY }}
        run: |
          Test-ModuleManifest -Path ".\powershell\Mondoo.Installer\Mondoo.Installer.psd1"
          Publish-Module -Path .\powershell\Mondoo.Installer -NuGetApiKey $env:NUGETAPIKEY
