name: Update Release Version

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version that should be released'
        required: true
        default: '1.2.3'

jobs:
  update-downstream:
    runs-on: ubuntu-latest
    ## Matrix task, repeats steps for each repo
    strategy:
      matrix:
        repo: ["mondoohq/homebrew-mondoo", "mondoohq/mac-pkg"]
        #repo: ["mondoohq/homebrew-mondoo", "mondoohq/archlinux-package", "mondoohq/mac-pkg"]
    steps:
      - uses: actions/checkout@v3
      - name: Repository Dispatch (Workflow Dispatch)
        uses: peter-evans/repository-dispatch@v2
        if: github.event_name == 'workflow_dispatch'
        with:
          token: ${{ secrets.REPO_API_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: update
          client-payload: '{"version": "${{ github.event.inputs.version }}"}'
      - name: Repository Dispatch (Release)
        uses: peter-evans/repository-dispatch@v2
        if: github.event_name == 'release'
        with:
          token: ${{ secrets.REPO_API_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: update
          client-payload: '{"version": "${{ github.event.release.tag_name }}"}'

  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Get Latest Tag
        id: vars
        uses: WyriHaximus/github-action-get-previous-tag@v1
      # runs go to generate the update
      - run: |
          echo '${{ steps.vars.outputs.tag }}' > VERSION
      # Commit changes
      - name: commit
        run: |
          echo 'VERSION is ${{ steps.vars.outputs.tag }}'
          git add VERSION
          git config --global user.email "tools@mondoo.com"
          git config --global user.name "Mondoo Tools"
          git commit -m "Update VERSION to ${{ steps.vars.outputs.tag }}"
          git push origin master -f
