name: Run Release Workflows

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      version:
        description: "Version that should be released"
        required: true
        default: "1.2.3"
        type: string

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Get Version (Workflow Dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo VERSION=${{ inputs.version }} >> $GITHUB_ENV
      - name: Get Version (Release Event)
        if: github.event_name == 'release'
        run: |
          echo VERSION=${{ github.event.release.tag_name }} >> $GITHUB_ENV
      - name: Set Version
        id: version
        run: |
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  create-release:
    runs-on: ubuntu-latest
    needs: get-version
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ inputs.version }}
          tag_name: ${{ inputs.version }}

  release_mondoo_pkgs:
    name: Trigger release_mondoo_pkgs workflow
    uses: ./.github/workflows/release_mondoo_pkgs.yaml
    needs: get-version
    with:
      version: ${{ needs.get-version.outputs.version }}

  update-version:
    name: Trigger update-version workflow
    uses: ./.github/workflows/update-version.yml
    needs: get-version
    with:
      version: ${{ needs.get-version.outputs.version }}

  build_container:
    name: Trigger build_container workflow
    uses: ./.github/workflows/build_container.yml

  pkg_macos:
    name: Trigger pkg_macos workflow
    uses: ./.github/workflows/pkg_macos.yaml
    needs: get-version
    with:
      version: ${{ needs.get-version.outputs.version }}

  pkg_arch-aur:
    name: Trigger pkg_arch-aur workflow
    uses: ./.github/workflows/pkg_arch-aur.yaml
    needs: get-version
    with:
      version: ${{ needs.get-version.outputs.version }}

  pkg_chocolatey:
    name: Trigger pkg_chocolatey workflow
    uses: ./.github/workflows/pkg_chocolatey.yaml
    needs: get-version
    with:
      version: ${{ needs.get-version.outputs.version }}

  pkg_msi:
    name: Trigger pkg_msi workflow
    uses: ./.github/workflows/pkg_msi.yaml
    needs: get-version
    with:
      version: ${{ needs.get-version.outputs.version }}

  test_install_sh:
    name: Trigger pkg_msi workflow
    uses: ./.github/workflows/test_install_sh.yml
    needs: update-version

  test-released-all:
    name: Trigger test-released-all workflow
    uses: ./.github/workflows/test-released-all.yaml
    with:
      version: ${{ needs.get-version.outputs.version }}
    needs:
      - get-version
      - release_mondoo_pkgs
      - build_container
      - pkg_macos
      - pkg_arch-aur
      - pkg_chocolatey
      - pkg_msi
      - test_install_sh

  integration-tests:
    name: Trigger integration test workflow
    runs-on: ubuntu-latest
    needs:
      - get-version
      - test-released-all
    steps:
      - name: Run integration test workfow
        env:
          GH_TOKEN: ${{ secrets.REPO_API_TOKEN }}
        run: gh workflow run test.yaml --repo "mondoohq/integration-test" --field version=${{ needs.get-version.outputs.version }}
