name: "Test Release: ALL - Trigger Release Build Tests"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to test"
        required: true
        default: "9.0.0"

jobs:
  test-arch:
    uses: ./.github/workflows/test-released-archlinux.yaml
    with:
      version: ${{ github.event.inputs.version }}
  test-docker:
    uses: ./.github/workflows/test-released-docker.yaml
    with:
      version: ${{ github.event.inputs.version }}
  test-install-sh:
    uses: ./.github/workflows/test-released-install-sh.yaml
    with:
      client: "cnspec"
      version: ${{ github.event.inputs.version }}
  test-install-ps1:
    uses: ./.github/workflows/test-released-install-ps1.yaml
    with:
      client: "cnspec"
      version: ${{ github.event.inputs.version }}
  test-osx-pkg:
    uses: ./.github/workflows/test-released-osx-pkg.yaml
    with:
      version: ${{ github.event.inputs.version }}
  test-brew:
    uses: ./.github/workflows/test-released-brew.yaml
    with:
      version: ${{ github.event.inputs.version }}
