name: "Test Release: install.ps1"

on:
  workflow_call:
    inputs:
      client:
        required: true
        type: string
        default: "cnspec"
      version:
        description: "Version to test"
        required: true
        default: "9.0.0"
        type: string
  workflow_dispatch:
    inputs:
      client:
        description: "Client to Test"
        type: choice
        options:
          - mondoo
          - cnspec
          - cnquery
      version:
        description: "Version to test"
        required: true
        default: "9.0.0"

jobs:
  install-sh-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        os: ["windows-latest"]
    steps:
      - uses: actions/checkout@v4
      - name: Version
        id: version
        run: |
          $v='${{ github.event.inputs.version }}'
          $version=$v.trim("v","V")
          echo "version=$version" >> $env:GITHUB_OUTPUT
      - name: Install.sh/${{ inputs.client }} on ${{ matrix.os }}
        run: |
          Set-ExecutionPolicy Unrestricted -Scope Process -Force;
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
          iex ((New-Object System.Net.WebClient).DownloadString('https://install.mondoo.com/ps1/${{ inputs.client }}'));
          Install-Mondoo -Product ${{ inputs.client }};
      - name: Verify the correct version is installed
        run: |
          $version=C:\Program Files\Mondoo\cnspec.exe version
          $version -like "*${{ steps.version.outputs.version }}*"
