name: "Test Release: Homebrew"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  formulae:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        package: ["cnquery", "cnspec"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Testing install of ${{ matrix.package }}....
        run: |
          brew tap mondoohq/mondoo
          brew install ${{ matrix.package }}

      - name: Executing ${{ matrix.package }}....
        run: |
          ${{ matrix.package }} version

  cask:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Testing install of mondoo cask....
        run: |
          brew install --cask mondoohq/mondoo/mondoo

      - name: Executing cnspec from Mondoo package....
        run: |
          /Library/Mondoo/bin/cnspec version
