name: "Test Release: install.sh"

on:
  workflow_call:
    inputs:
      version:
        description: "Version to test"
        required: true
        default: "9.0.0"
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: "Version to test"
        required: true
        default: "9.0.0"

jobs:
  install-sh-apt:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ["cnspec", "cnquery"]
        distro:
          [
            "debian:10",
            "debian:11",
            "ubuntu:18.04",
            "ubuntu:20.04",
            "ubuntu:22.04",
          ]
    steps:
      - uses: actions/checkout@v4
      - name: Version
        id: version
        run: |
          V=${{ github.event.inputs.version }}
          VERSION=$(echo $V | sed 's/^v//')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Install.sh/${{ matrix.package }} on ${{ matrix.distro }}
        run: |
          docker run --rm -v $(pwd):/work -w /work ${{ matrix.distro }} \
          bash -c "apt-get update && apt-get install -y curl && curl -sSL https://install.mondoo.com/sh/${{ matrix.package }} | bash - && ${{ matrix.package }} version | grep -q ${{ steps.version.outputs.version }}"

  install-sh-yum:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ["cnspec", "cnquery"]
        distro:
          [
            "centos:7",
            "quay.io/centos/centos:stream9",
            "fedora:32",
            "fedora:33",
            "rockylinux:8",
            "rockylinux:9",
            "redhat/ubi8",
            "redhat/ubi9",
            "oraclelinux:8",
            "oraclelinux:9",
          ]
        ## Note: centos:8 is obsoleted by Centos Stream 9 and EOL, do not use, refer to https://www.centos.org/centos-linux-eol/
    steps:
      - uses: actions/checkout@v4
      - name: Version
        id: version
        run: |
          V=${{ github.event.inputs.version }}
          VERSION=$(echo $V | sed 's/^v//')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Install.sh/${{ matrix.package }} on ${{ matrix.distro }}
        run: |
          docker run --rm -v $(pwd):/work -w /work ${{ matrix.distro }} \
          bash -c "curl -sSL https://install.mondoo.com/sh/${{ matrix.package }} | bash - && ${{matrix.package }} version | grep -q ${{ steps.version.outputs.version }}"

  install-sh-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        os: ["macos-latest"]
        package: ["cnspec", "cnquery"]
    steps:
      - uses: actions/checkout@v4
      - name: Version
        id: version
        run: |
          V=${{ github.event.inputs.version }}
          VERSION=$(echo $V | sed 's/^v//')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Install.sh/${{ matrix.package }} on ${{ matrix.os }}
        run: |
          bash -c "$(curl -sSL https://install.mondoo.com/sh/${{ matrix.package }})"
          ${{ matrix.package }} version
      - name: Verify the correct version is installed
        run: |
          ${{ matrix.package }} version | grep -q ${{ steps.version.outputs.version }}

