name: Test Mondoo Releases with Container Builds

on:
  workflow_run:
    workflows: ['Update Release Version'] # runs after release
    types:
      - completed
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'install.sh'

jobs:
  build_container:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        dockerfile:
          #- "almalinux.arm64.Dockerfile"
          - "almalinux.Dockerfile"
          - "amazonlinux2.Dockerfile"
          - "debian.Dockerfile"
          - "opensuse_leap.Dockerfile"
          - "redhat.Dockerfile"
          - "ubuntu.Dockerfile"
    name: Install Mondoo
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: ${{ env.SLACK_BOT_CHANNEL_ID }}
          payload: |
            {
              "attachments": [
                {
                  "color": "#FFFF00",
                  "blocks": [
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "<${{ env.WORKFLOW_RUN_URL }}|${{ env.WORKFLOW_RUN_NAME }}>"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Status:*\n`In Progress`"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          # C07R9GSGKEU == #mondoo-ops
          SLACK_BOT_CHANNEL_ID: "C07R9GSGKEU"
          WORKFLOW_RUN_URL: ${{ github.event.workflow_run.html_url }}
          WORKFLOW_RUN_NAME: ${{ github.event.workflow_run.name }}
          JOB_STATUS: ${{ job.status }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: test/install_sh/${{ matrix.dockerfile }}
          push: false
          tags: |
            mondoohq/mondoo-install-test:${{ matrix.dockerfile }}


      - uses: slackapi/slack-github-action@v1.27.0
        if: always()
        with:
          channel-id: ${{ env.SLACK_BOT_CHANNEL_ID }}
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
             {
              "attachments": [
                {
                  "color": "${{ env.JOB_STATUS == 'success' && '#00FF00' || env.JOB_STATUS == 'failure' && '#FF0000' || '#FFA500' }}",
                  "blocks": [
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "<${{ env.WORKFLOW_RUN_URL }}|${{ env.WORKFLOW_RUN_NAME }}>"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Status:*\n`${{ env.JOB_STATUS }}`"
                        }
                      ]
                    }
                  ]
                }
                ]
              }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          # C07R9GSGKEU == #mondoo-ops
          SLACK_BOT_CHANNEL_ID: "C07R9GSGKEU"
          WORKFLOW_RUN_URL: ${{ github.event.workflow_run.html_url }}
          WORKFLOW_RUN_NAME: ${{ github.event.workflow_run.name }}
          JOB_STATUS: ${{ job.status }}