name: "Test Release: Homebrew"

on:
  workflow_call:
    inputs:
      version:
        description: "Version to test"
        required: true
        default: "9.0.0"
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: "Version to test"
        required: true
        default: "9.0.0"

jobs:
  formulae:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        package: ["cnquery", "cnspec"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Testing install of ${{ matrix.package }}....
        run: |
          brew tap mondoohq/mondoo
          brew install ${{ matrix.package }}

      - name: Version
        id: version
        run: |
          V=${{ github.event.inputs.version }}
          VERSION=$(echo $V | sed 's/^v//')
          echo "package_version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Executing ${{ matrix.package }}....
        run: |
          ver=$(${{ matrix.package }} version)
          contains($ver, ${{ steps.version.outputs.package_version}})

  cask:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Testing install of mondoo cask....
        run: |
          brew install --cask mondoohq/mondoo/mondoo

      - name: Version
        id: version
        run: |
          V=${{ github.event.inputs.version }}
          TRIMMED=$(echo $V | sed 's/^v//')
          echo "package_version=${TRIMMED}" >> $GITHUB_OUTPUT
      - name: Executing cnspec from Mondoo package....
        run: |
          ver=$(/Library/Mondoo/bin/cnspec version)
          contains($ver, ${{ steps.version.outputs.package_version}})
