name: Update Release Version

on:
  workflow_call:
    inputs:
      version:
        description: "Version that should be released"
        required: true
        default: "1.2.3"
        type: string
      skip-commit:
        description: "Skip commit?"
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      version:
        description: 'Version that should be released'
        required: true
        default: '1.2.3'
        type: string

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0
      - name: Version
        run: |
          V=$(echo ${{ github.event.inputs.version }} | sed 's/v//g')
          echo "VERSION=${V}" >> $GITHUB_ENV
      - name: Verify valid version
        id: vars
        run: |
          if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version: $VERSION"
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Commit VERSION file
        if: ${{ ! inputs.skip-commit }}
        run: |
          echo ${VERSION} > VERSION
          echo "VERSION is $VERSION"
          git add VERSION
          git config --global user.email "tools@mondoo.com"
          git config --global user.name "Mondoo Tools"
          git commit -m "Update VERSION to $VERSION"
          git push -f
